AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: Flask-app

  MyTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: python
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Name: api
          Image: "public.ecr.aws/z2d7x1g0/api"
          PortMappings:
            - ContainerPort: 5001
              HostPort: 5001
              Protocol: tcp
        - Name: app
          Image: "public.ecr.aws/z2d7x1g0/app"
          PortMappings:
            - ContainerPort: 5002
              HostPort: 5002
              Protocol: tcp
        - Name: db
          Image: "public.ecr.aws/z2d7x1g0/db"

  MyService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref MyTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-0a72bbfa89627dd6b
          SecurityGroups:
            - sg-0781e86c8be918acd

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECSTaskPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
